# frozen_string_literal: true

#==============================================================================
# Copyright (C) 2017 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Underware.
#
# Alces Underware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Underware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Underware, please visit:
# https://github.com/alces-software/underware
#==============================================================================

require 'underware/nodeattr_interface'
require 'underware/exceptions'

RSpec.describe Underware::NodeattrInterface do
  include Underware::AlcesUtils

  describe '#nodes_in_group' do
    it 'returns only the nodes in the primary group' do
      genders = <<~GENDERS.strip_heredoc
        node[01-02] nodes
        node03 special_nodes,nodes
      GENDERS
      File.write(Underware::FilePath.genders, genders)

      nodes = described_class.nodes_in_group('nodes')
      expect(nodes).to contain_exactly('node01', 'node02')
    end

    it 'does not error when any node has no primary group' do
      # This is a valid genders file, and even though it shouldn't be
      # generated by Underware given its current template, we should still
      # handle it correctly (even if only to give us more robust tests
      # elsewhere).
      genders = <<~GENDERS.strip_heredoc
        node[01-02] nodes
        groupless_node
      GENDERS
      File.write(Underware::FilePath.genders, genders)

      expect do
        described_class.nodes_in_group('nodes')
      end.not_to raise_error
    end
  end

  # XXX Rewrite below tests to explicitly setup genders file (like above),
  # rather than using generic mystery guest fixture which makes it hard to tell
  # what's going on.

  context 'using mock genders' do
    before do
      FileSystem.setup(&:with_genders_fixtures)
    end

    describe '#nodes_in_gender' do
      it 'returns names of all nodes in the given gender group' do
        expect(
          described_class.nodes_in_gender('masters')
        ).to eq(['login1'])
        expect(
          described_class.nodes_in_gender('nodes')
        ).to eq(['testnode01', 'testnode02', 'testnode03'])
        expect(
          described_class.nodes_in_gender('cluster')
        ).to eq(['login1', 'testnode01', 'testnode02', 'testnode03'])
      end

      it 'raises if cannot find gender group' do
        expect do
          described_class.nodes_in_gender('non_existent')
        end.to raise_error Underware::NoGenderGroupError
      end
    end

    describe '#genders_for_node' do
      it 'returns groups for given node, ordered as in genders' do
        testnode_groups = ['testnodes', 'nodes', 'cluster']
        expect(
          described_class.genders_for_node('testnode01')
        ).to eq(testnode_groups)
        expect(
          described_class.genders_for_node('testnode02')
        ).to eq(['pregroup'] + testnode_groups + ['postgroup'])
      end

      it 'raises if cannot find node' do
        expect do
          described_class.genders_for_node('non_existent')
        end.to raise_error Underware::NodeNotInGendersError
      end
    end
  end

  describe '#validate_genders_file' do
    subject do
      described_class.validate_genders_file(genders_path)
    end

    let(:genders_file) { Tempfile.new }
    let(:genders_path) { genders_file.path }

    it 'returns true and no error when given a valid genders file' do
      File.write(genders_path, "node01 nodes,other,groups\n")

      expect(subject).to eq true
    end

    it 'raises an error if the genders file is invalid' do
      # This genders file is invalid as `node01` is given `nodes` group twice.
      File.write(genders_path, "node01 nodes,other,groups\nnode01 nodes\n")

      expect { subject }.to raise_error Underware::SystemCommandError
    end

    it 'raises if given file does not exist' do
      # Get path to the test genders file and then delete it, so we have a path
      # to a file which almost certainly won't exist (barring some very
      # improbable race condition).
      path = genders_path
      genders_file.delete

      expect do
        described_class.validate_genders_file(path)
      end.to raise_error(Underware::FileDoesNotExistError)
    end
  end
end
