#!/bin/bash
#==============================================================================
# Copyright (C) 2007-2015 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Alces Underware.
#
# Alces Underware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Alces Underware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Alces Underware, please visit:
# https://github.com/alces-software/underware
#==============================================================================
source=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)
target=/opt/underware
dist_url=https://s3-eu-west-1.amazonaws.com/packages.alces-software.com/underware/dist
source $source/scripts/lib/ui.functions.sh
source $source/scripts/lib/fetch.functions.sh
source $source/scripts/lib/install.functions.sh

# Note: on a `fresh` install dependencies will be retrieved and built from
# scratch; on a `dist` install they will (mostly) be retrieved pre-built from
# `$dist_url` above.
#
# Given a working `fresh` installation, the pre-built dependencies needed for a
# `dist` installation can be packaged using commands like the following, after
# which they should be uploaded to `$dist_url/$os/$package`:
#
# ```
# tar -C /opt/underware -cvzf genders.tar.gz opt/genders
# tar -C /opt/underware -cvzf ruby-2.4.1.tar.gz opt/ruby
# tar -C /opt/underware -cvzf libyaml.tar.gz opt/lib
# tar -C /opt/underware -cvzf pdsh.tar.gz opt/pdsh
# ```
deps="libyaml ruby bundler genders pdsh components"

if [ -z "$2" ]; then
  echo "$0: invalid parameters"
  cat <<EOF
Usage: $0 <OS> <fresh|dist>

OS must be one of the systems supported by underware: 'el6', 'el7'

Supply 'fresh' or 'dist' to select whether to build dependencies from
source or to download prebuilt distributions of the dependencies.
EOF
  exit 1
else
  os="$1"
  dep_source="$2"
fi

cat <<EOF
[33m===============================================================================
 STARTING UNDERWARE INSTALLATION
===============================================================================[0m
EOF

source "${source}/scripts/os/${os}.sh"

mkdir -p ${source}/tmp/log ${source}/tmp/src ${source}/tmp/build
dep_logs="${source}/tmp/log"
dep_build="${source}/tmp/build"
dep_src="${source}/tmp/src"

# Install pre-requisites
title "Installing prerequisites"
doing 'Base'
install_base_prerequisites &> "${dep_logs}/base-prereqs.log"
say_done $?
# Always installing build prerequisites for the moment as always installing
# fresh gems each time.
# if [ "${dep_source}" == "fresh" ]; then
    doing 'Build'
    install_build_prerequisites &> "${dep_logs}/build-prereqs.log"
    say_done $?
# fi
doing 'Runtime'
install_runtime_prerequisites &> "${dep_logs}/runtime-prereqs.log"
say_done $?

title "Creating initial directory structure"
doing 'Create'
mkdir -p /var/log/underware
mkdir -p /var/lib/underware/rendered/system
mkdir -p /var/lib/underware/cache/templates
mkdir -p /var/lib/underware/events
mkdir -p /var/lib/underware/repo
mkdir -p /var/lib/underware/plugins
mkdir -p /var/lib/underware/answers/{groups,nodes}
mkdir -p /var/lib/underware/assets
mkdir -p /var/lib/underware/data

# Link hosts files in to Underware data dir. This allows the Underware-rendered
# hosts file to be used when using this machine, and this may also be served by
# the Metalware deployment server if Metalware is also installed.
ln -s /etc/hosts /var/lib/underware/rendered/system/

mkdir -p "${target}"
cp -R "${source}/"{Gemfile,Gemfile.lock,bin,etc,libexec,lib,data} "${target}"
cp ${source}/etc/logrotate.d/* /etc/logrotate.d/
say_done $?

for dep in ${deps}; do
    source "${source}/scripts/dependencies/${dep}.sh"
    if ! detect_${dep}; then
        fetch_${dep}
    fi
done

for dep in ${deps}; do
    if ! detect_${dep}; then
        install_${dep}
    fi
done

title "Installing profile hooks"
doing 'Install'
cp "${source}/dist/profile"/* /etc/profile.d
say_done $?

if [ "$(type -t lsof)" ]; then
    ppid=`ps -p $$ -o ppid=`
    user_shell=`lsof -p $ppid | awk '(NR==2) {print $1}'`
fi

case $user_shell in
    sh|bash|ksh|zsh)
        rc_script_ext=sh
        ;;
    tcsh|csh)
        rc_script_ext=csh
        ;;
    *)
        rc_script_ext=sh
        ;;
esac

cat <<EOF
[33m
===============================================================================
 UNDERWARE INSTALLATION COMPLETE
===============================================================================
[0m[1m
Global profile scripts have been installed in:

/etc/profile.d/alces-underware.sh
/etc/profile.d/alces-underware.csh

Please login again, or manually run the following:

source /etc/profile.d/alces-underware.${rc_script_ext}

Afterwards, execute 'underware --help' for further information.
[0m
EOF
