#!/bin/bash
#==============================================================================
# Copyright (C) 2019 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Underware.
#
# Underware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Underware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Underware, please visit:
# https://github.com/alces-software/underware
#==============================================================================
inital_env=$(env)
alces_INSTALL_DIR="${alces_INSTALL_DIR:-/opt/flight/tools}"
alces_VERSION="${alces_VERSION:-0.6.0-rc1}"

#==============================================================================
# DON'T EDIT ANYTHING UNDER HERE
#==============================================================================

# Check for Flight Core
if [ ! -x /opt/flight/bin/bundle ]; then
    echo "Unable to install; no Flight Core environment was found."
    exit 1
fi

source /etc/profile.d/alces-flight.sh

# Detect whether script is being curled or run locally from within `scripts` directory
SCRIPT_PARENT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
SCRIPT_PATH=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SCRIPT_BASE=$(basename $SCRIPT_PATH)

if [[ $SCRIPT_BASE != "scripts" ]] ; then 
    CLONE=true
    CHECKOUT=true
else
    CLONE=""
    alces_INSTALL_DIR=$SCRIPT_PARENT_PATH
    # Check if alces_VERSION was specified on CLI
    if echo "$initial_env" |grep -q '^alces_VERSION' ; then
        CHECKOUT=true
    else
        CHECKOUT=""
    fi
fi

# Create install dir
mkdir -p $alces_INSTALL_DIR
cd $alces_INSTALL_DIR

if [ ! -z $CLONE ] ; then
    # Install tool
    git clone https://github.com/alces-software/underware
fi

cd underware

if [ ! -z $CHECKOUT ] ; then
    git checkout $alces_VERSION
fi

# Install dependencies
flexec bundle install --path=vendor --without development test

# Setup command file
cat << EOF > /opt/flight/libexec/commands/underware
: '
: NAME: underware
: SYNOPSIS: Cluster configuration and templating 
: VERSION: $alces_VERSION
: '
#==============================================================================
# Copyright (C) 2019 Stephen F. Norledge and Alces Software Ltd.
#
# This file/package is part of Underware.
#
# Underware is free software: you can redistribute it and/or
# modify it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.
#
# Underware is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this package.  If not, see <http://www.gnu.org/licenses/>.
#
# For more information on the Underware, please visit:
# https://github.com/alces-software/underware
#==============================================================================
cd $alces_INSTALL_DIR/underware/
flexec ruby bin/underware "\$@"
EOF
